buildscript {
    ext.kotlin_version = '1.7.22'
    repositories {
        google()
        mavenCentral()
    }
    
    ext {
        // Update these versions as needed
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        targetSdkVersion = 33
        compileSdkVersion = 33
        kotlin_version = '1.8.10'
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath 'com.google.gms:google-services:4.3.15'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.9'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

    }

    // dependencies {
    //     classpath 'com.android.tools.build:gradle:7.4.2'  // Updated this line
    //     classpath 'com.google.gms:google-services:4.3.10'
    // }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
