// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCZxJJuGhSM4XqIt142vIfmahDijz0Rak',
    appId: '1:91163665609:android:11ec8b060b8dfe145f5918',
    messagingSenderId: '91163665609',
    projectId: 'my-first-project-5d32d',
    storageBucket: 'my-first-project-5d32d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA6XVcDofzX_kU9uJM8wlw2WylFDoNaH8',
    appId: '1:91163665609:ios:03599091e4c4635f5f5918',
    messagingSenderId: '91163665609',
    projectId: 'my-first-project-5d32d',
    storageBucket: 'my-first-project-5d32d.appspot.com',
    androidClientId: '91163665609-3eo20v6svvjc7k5tvmbrm0j92fj8l1kg.apps.googleusercontent.com',
    iosClientId: '91163665609-25gf7rbq6spqpej2e9c4knhscpl09d73.apps.googleusercontent.com',
    iosBundleId: 'com.mmovie.solvio',
  );
}
